name: Regression Tests

on:
  push:
    branches:
      - "**"
  pull_request_target:
    branches:
      - master

jobs:
  regression-tests:
    name: Regression tests (CLI)
    strategy:
      matrix:
        product: [Live-Common, Live-Desktop, Custom-G, Custom-W]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bs4

      - name: Install Xpub Scan dependencies and build it
        run: |
          yarn && yarn build

      - name: Regression Tests — ${{ matrix.product }}
        run: |
          # use custom provider
          export XPUB_SCAN_CUSTOM_API_KEY_V2=${{ secrets.XPUB_SCAN_CUSTOM_API_KEY_V2 }}

          python .github/workflows/regression_tests/check.py ${{ matrix.product }}
