name: Tests

on:
  push:
    branches:
      - "**"
  pull_request_target:
    branches:
      - master

jobs:
  check-dependencies:
    name: Check dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install depcheck
        run: |
          npm install -g depcheck

      - name: Check dependencies
        run: |
          npm i > /dev/null 2>&1
          depcheck --ignores="ts-node,tiny-secp256k1"
          check-outdated --ignore-packages tiny-secp256k1,@types/tiny-secp256k1
          npm audit --audit-level=low --json

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: check-dependencies
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Prettify
        run: yarn prettier

      - name: Run checks
        run: yarn ci

  regression-tests:
    name: Regression tests (CLI)
    needs: unit-tests
    strategy:
      matrix:
        product: [Live-Common, Live-Desktop, Custom-G, Custom-W]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bs4

      - name: Install Xpub Scan dependencies and build it
        run: |
          yarn && yarn build

      - name: Regression Tests — ${{ matrix.product }}
        run: |
          # use custom provider
          export XPUB_SCAN_CUSTOM_API_KEY_V2=${{ secrets.XPUB_SCAN_CUSTOM_API_KEY_V2 }}

          python .github/workflows/regression_tests/check.py ${{ matrix.product }}
