name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-dependencies:
    name: Check dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install depcheck
        run: |
          npm i -g check-outdated
      - name: Check dependencies
        run: |
          npm i
          yarn check --verify-tree
          check-outdated --ignore-packages chalk,jest,bitcoinjs-lib
          npm audit --audit-level=low --json

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: check-dependencies
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Prettify
        run: yarn prettier

      - name: Run checks
        run: yarn ci
